### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by mchorse** [tuxcrafting/your-mom#7]
Is there any tutorials on `your-mom` or maybe manual about `your-mom`?

How am I gonna write on `your-mom` if I don't even know the basics of `your-mom`?!

P.S.: nice name for a _golfing language_ 😉

**Comment by tuxcrafting** [comment]
@mchorse You can find a documentation about the commands in [the wiki](https://github.com/tuxcrafting/your-mom/wiki).
